# Usar uma imagem base do Python
FROM python:3.9-slim

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos de aplicação para o container
COPY . /app

# Instalar as dependências (se houver um requirements.txt)
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta 5000 para a aplicação
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "app.py"]
